### ISSUE TITLE
[US] COMO servidor da secretaria acadêmica, QUERO visualizar todos os servidores cadastrados no sistema, PARA verificar quem pode emitir comunicados e o respectivo nível de acesso no sistema.

### ISSUE THREAD

**Issue by carlasoliveira** [Mythus-Inc/notify#11]
### Épico
- #3

### Descrição
COMO servidor da secretaria acadêmica, QUERO visualizar todos os servidores cadastrados no sistema, PARA verificar quem pode emitir comunicados e o respectivo nível de acesso no sistema.

### Tarefas relacionadas
- [x] Tarefa 1: Criar uma tela para visualizar todos os servidores cadastrados no sistema
- [x] Tarefa 2: Listar na tela de usuários todos os servidores cadastrados no sistema (nome, SIAPE, cargo/função, permissões)
- [x] Tarefa 3: Incluir botão para expansão das informações de determinado servidor quando clicado - exibir informações de contato (telefone e e-mail) e botão de editar

### Critérios de aceitação
- [x] A tela segue o design elaborado
- [x] As informações são exibidas conforme descrito nas Tarefas 2 e 3
- [x] Os dados são exibidos corretamente após a consulta no banco de dados

**Comment by VitorTavaresO** [comment]
Bugs a serem resolvidos:

- [ ] A tela não está adequada ao mobile first, fazer as devidas correções para adequar.

- [ ] Ao utilizar o filtro de funcionários, o style da lista de funcionários é alterado, o style deve permanecer o mesmo quando o filtro for aplicado.

**Comment by VitorTavaresO** [comment]
Bugs a serem resolvidos:

- [ ] No mobile o header e o footer não ficam visíveis na tela(O problema pode estar diretamente nesses componentes)
- [ ] No web a listagem passa sobre o header

**Comment by marceloTerencianiIFPR** [comment]
- [x] História de usuário mensurável e criada pelo PO
- [x] Frequência de commits adequada
- [x] Foi atribuída a um ou mais desenvolvedores
- [x] Foi criada branch para a história
- [x] A história passou pelo quadro Kanban
- [x] Foram Geradas Estimativas
- [x] Foi criado pull request para a dev
- [x] Foi criado pull request para a main
