### ISSUE TITLE
[US] COMO servidor do campus, QUERO visualizar os comunicados enviados, PARA que eu possa verificar quais informações foram enviadas para quais grupos de destinatários.

### ISSUE THREAD

**Issue by carlasoliveira** [Mythus-Inc/notify#22]
### Épico
- #5 

### Descrição
COMO servidor do campus, QUERO visualizar os comunicados enviados, PARA que eu possa verificar quais informações foram enviadas para quais grupos de destinatários.

### Tarefas relacionadas
- [x] Tarefa 1: Listar os comunicados enviados pelo próprio usuário
- [x] Tarefa 2: Ordenar os comunicados enviados por: mais antigo/recente
- [ ] Tarefa 3: Criar um endpoint para listar os comunicados enviados pelo usuário
- [x] Tarefa 4: Permitir que o uso de parâmetros de ordenação, como "mais recente" ou "mais antigo"
- [ ] Tarefa 5: Garantir que serão exibidos somente os comunicados enviados pelo usuário logado 
- [x] Tarefa 6: Adicionar suporte para a exibição dos comunicados em páginas

### Critérios de aceitação
- [x] A tela segue o design elaborado
- [x] A lista de comunicados é consultada no banco de dados e exibida corretamente no frontend
- [ ] São exibidos somente os comunicados enviados pelo usuário logado 
- [x] A exibição dos comunicados em páginas acontece corretamente
- [x] É realizado o tratamento adequado dos erros e exceções
- [x] As mensagens de erro são exibidas corretamente no backend

**Comment by VitorTavaresO** [comment]
**APROVADO COM RESALVAS**

Devido a problemas com a autenticação, se torna complexo o funcionamento da listagem apenas dos comunicados emitidos pelo usuário, devido a isso as tarefas relacionadas a isso foram anotadas e serão tratadas na próxima sprint quando a autenticação de usuário for aplicada ao sistema.
