### ISSUE TITLE
[US] COMO usuário do sistema, QUERO acessar uma aplicação com design simples, intuitivo e padronizado, PARA que não haja dificuldades na realização das atividades relacionadas a ele - aplicação WEB.

### ISSUE THREAD

**Issue by carlasoliveira** [Mythus-Inc/notify#6]
### Épico
- #3 

### Descrição
COMO usuário do sistema, QUERO acessar uma aplicação com design simples, intuitivo e padronizado, PARA que não haja dificuldades na realização das atividades relacionadas a ele - aplicação WEB.

### Tarefas relacionadas
- [x] Tarefa 1: Elaborar o design do componente **header** padronizado para o sistema
- [x] Tarefa 2: Elaborar o design do componente **footer** padronizado para o sistema
- [x] Tarefa 3: Manter as cores da identidade visual do Instituto Federal
- [x] Tarefa 4: Elaborar o design da tela de cadastro de usuários
- [x] Tarefa 5: Elaborar o design da tela de login de usuários
- [x] Tarefa 6: Elaborar o design da tela de perfil do usuário
- [x] Tarefa 7: Elaborar o design da tela de listagem dos usuários do sistema
- [x] Tarefa 8: IMPLEMENTAR uma tela com os componentes header e footer, que será tratada como a **home** do sistema

### Critérios de aceitação
- [x] As cores são utilizadas conforme a identidade visual do Instituto Federal
- [x] O design propõe uma interface simples e intuitiva para o usuário

**Comment by Xanxesss** [comment]
Protótipos das telas de **Login** e **Listagem de Servidores** [contendo **Header** e **Footer**].

![Image](https://github.com/user-attachments/assets/dc39d19d-f8c1-4009-a77e-69d52ce05012)
![Image](https://github.com/user-attachments/assets/dbf2031e-fe5a-47fe-82eb-17bd665096ac)

**Comment by marceloTerencianiIFPR** [comment]
- [x] História de usuário mensurável e criada pelo PO
- [x] Frequência de commits adequada
- [x] Foi atribuída a um ou mais desenvolvedores
- [x] Foi criada branch para a história
- [x] A história passou pelo quadro Kanban
- [x] Foram Geradas Estimativas
- [x] Foi criado pull request para a dev
- [x] Foi criado pull request para a main
