### ISSUE TITLE
[US] COMO usuário do sistema, QUERO obter meu cadastro na plataforma, PARA que eu possa ter acesso aos recursos oferecidos.

### ISSUE THREAD

**Issue by carlasoliveira** [Mythus-Inc/notify#7]
### Épico
- #3 

### Descrição
COMO usuário do sistema, QUERO obter meu cadastro na plataforma, PARA que eu possa ter acesso aos recursos oferecidos.

### Tarefas relacionadas
- [x] Tarefa 1: Criar uma tela destinada para o cadastro de usuários (servidores)
- [x] Tarefa 2: Implementar um formulário para o cadastro de usuários com os seguintes campos: nome, CPF, SIAPE, telefone, e-mail, cargo/função, senha, confirmação de senha
- [x] Tarefa 3: Exibir no ato do preenchimento se o CPF informado for inválido
- [x] Tarefa 4: Exibir no ato do preenchimento se a senha informada não cumpre os requisitos necessários

### Critérios de aceitação
- [x] A tela segue o design elaborado
- [x] O formulário contém os campos descritos na Tarefa 2
- [x] É informado para o usuário o padrão de senha necessário para o cadastro: 8 caracteres, com pelo menos 1 letra, 1 número e 1 caractere especial 
- [x] Os campos CPF e telefone possuem máscara de formatação
- [x] Os campos do formulário possuem um placeholder para exemplo

**Comment by marceloTerencianiIFPR** [comment]
- [x] História de usuário mensurável e criada pelo PO
- [x] Frequência de commits adequada
- [x] Foi atribuída a um ou mais desenvolvedores
- [x] Foi criada branch para a história
- [x] A história passou pelo quadro Kanban
- [x] Foram Geradas Estimativas
- [x] Foi criado pull request para a dev
- [x] Foi criado pull request para a main
